site_name: DXNN Application (DX-APP) User Manual
use_directory_urls: false
docs_dir: source # markdown 원문 폴더
site_dir: docs # html로 변환된 폴더
theme: 
  name : material
  language: en
  font:
    text: Noto Sans Display
    code: Roboto Mono 
  logo: ./img/deepx.png
  favicon: ./img/favicon.png
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
     - toc.integrate
     - content.code.annotate
     - navigation.tabs
     - navigation.tabs.sticky
     - content.tabs.link
     - content.code.copy
site_url: 'https://developer.deepx.ai/'
nav:
  - DXNN Application Overview: docs/01_DXNN_Application_Overview.md
  - DX-APP Installation and Build: docs/02_DX-APP_Installation_and_Build.md
  - DX-APP C++ Example: 
    - Guide: docs/03_DX-APP_CPP_Example_Usage_Guide.md
    - Test: docs/04_DX-APP_CPP_Example_Test.md
  - DX-APP Python Example:
    - Guide: docs/05_DX-APP_Python_Example_Usage_Guide.md
    - Test: docs/06_DX-APP_Python_Example_Test.md
  - DX-APP Post-processing:
    - C++: docs/07_DX-APP_CPP_PostProcess_Overview.md
    - Python Binding: docs/08_DX-APP_Pybind_PostProcess_Overview.md
  - DX-APP Project README: docs/09_DX-APP_Project_Overview.md
  - Change Log: docs/Appendix_Change_Log.md

plugins:
  - search
  - include-markdown
  - with-pdf:
      author: DEEPX.ai
      copyright: ⓒ Copyright 2026 DEEPX All Rights Reserved.
      #
      #cover: false
      cover_title: DXNN Application (DX-APP) User Manual
      cover_subtitle: v3.0.0 (Jan 2026)
      cover_logo: img/deepx.png
      custom_template_path: docs/stylesheets
      output_path: ../DEEPX_DX-APP_UM_v3.0.0.pdf
extra:
  homepage: https://developer.deepx.ai
  generator: false
  social:
     - icon: fontawesome/brands/linkedin
       link: https://www.linkedin.com/company/deepx-corporation/
extra_css: 
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - def_list
  - toc:
        permalink: "true"
        baselevel: 1
        separator: ">_"
        toc_depth: 3
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: ⓒ Copyright 2026 <a href="http://deepx.ai">DEEPX</a>. All Rights Reserved.
